name: Update Footer on Release

on:
  release:
    types:
      - published

jobs:
  update_footer:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Update footer
      run: |
        FOOTER_FILE="index.html"
        RELEASE_TITLE="${{ github.event.release.name }}"
        
        sed -i "s/PLACEHOLDER_TEXT/${RELEASE_TITLE}/g" "${FOOTER_FILE}"

    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "noreply@example.com"
        git add .
        git commit -m "Update footer with release title"
        git push
